


services:
  mongo-database:
    image: mongo:7.0.0
    container_name: mongo-database
    ports:
    - "4002:27017"
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: password

  primes-database:
    image: postgres:alpine
    ports:
      - "4004:5432"
    environment:
      POSTGRES_PASSWORD: password
      POSTGRES_DB: primes
  
arithmetic-service:
image: arithmetic-service
build:
context: .. /arithmetic-service
dockerfile: Dockerfile
container_name: arithmetic-service
ports:
- "4000:3000"
environment:
- PORT=3000
restart: "no"
